"""UI theme configuration for the classroom adventure."""

UI_THEME = {
    "window": {
        "background": "#101010",
        "fallback_text": "#ffffff",
    },
    "layout": {
        "header_width": 0.8,
        "header_top_margin": 0.04,
        "content_width": 0.68,
        "options_bottom_margin": 0.0,
        "option_spacing": 0.02,
        "dialogue_options_gap": 0.02,
        "container_background": "",
    },
    "header": {
        "panel_background": "#202020cc",
        "panel_outline": "",
        "corner_radius": 12,
        "padding": 4,
        "outer_margin": 8,
        "title_font": ("Segoe UI", 15, "bold"),
        "byline_font": ("Segoe UI", 10, ""),
        "title_foreground": "#f0f0f0",
        "byline_foreground": "#cccccc",
        "stats_font": ("Segoe UI", 10, "bold"),
        "stats_foreground": "#f0f0f0",
    },
    "dialogue": {
        "panel_background": "#101010cc",
        "panel_outline": "",
        "corner_radius": 28,
        "padding": 28,
        "font": ("Segoe UI", 14, ""),
        "foreground": "#f8f8f2",
    },
    "options": {
        "panel_background": "#101010cc",
        "panel_outline": "",
        "corner_radius": 24,
        "padding": 18,
        "button_corner_radius": 18,
        "button_font": ("Segoe UI", 12, ""),
        "button_height": 56,
        "button_padding": 22,
        "button_foreground": "#f5f5f5",
        "button_background": "#252525cc",
        "button_hover_background": "#343434e0",
        "button_active_background": "#454545ff",
        "button_disabled_background": "#151515cc",
        "button_disabled_foreground": "#7a7a7a",
        "button_horizontal_padding": 16,
    },
    "inventory": {
        "panel_background": "#101010cc",
        "panel_outline": "",
        "corner_radius": 18,
        "padding": 14,
        "title_font": ("Segoe UI", 16, "bold"),
        "title_foreground": "#f0f0f0",
        "list_font": ("Segoe UI", 12, ""),
        "list_foreground": "#f5f5f5",
        "hint_font": ("Segoe UI", 10, ""),
        "hint_foreground": "#bbbbbb",
        "detail_font": ("Segoe UI", 11, ""),
        "detail_foreground": "#dcdcdc",
        "used_foreground": "#777777",
    },
}
